blank_issues_enabled: false
contact_links:
  - name: ğŸ™ - Dev Feedback
    url: https://github.com/orgs/near/discussions/new?category=dev-feedback
    about: NEAR loves feedback! ğŸ’œ Please submit your ideas, suggestions, or general feedback regarding your experience building on NEAR.
  - name: â“- Dev Support on Telegram
    url: https://t.me/addlist/VyVjNaP190JlOGMx
    about: Get support from one of NEAR's commuity Dev Channels on Telegram.
  - name: â“ - Dev Support on Discord
    url: https://near.chat
    about: Get support from one of NEAR's commuity Dev Channels on Discord.
